apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: devops-module3
spec:
  interval: 3m
  chart:
    spec:
      chart: rabbitmq
      version: 16.0.2 # https://artifacthub.io/packages/helm/bitnami/rabbitmq
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    auth:
      username: user
      password: xsj74jsqg7
      erlangCookie: secretcookie123
    persistence:
      enabled: true
      size: 1Gi