apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 3m

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-oci
  namespace: flux-system
spec:
  interval: 3m
  url: oci://registry-1.docker.io/bitnamicharts
  ref:
    semver: "^6.5.0"