apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: devops-module3
spec:
  releaseName: mongodb
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 16.5.6  # https://artifacthub.io/packages/helm/bitnami/mongodb
  interval: 5m
  values:
    auth:
      rootPassword: 0yCQVo8llCD93iU
      username: tung
      password: XOQCG4RP1L5Dpzy
      database: devops-training
    architecture: standalone
    persistence:
      enabled: true
      size: 3Gi
